### ISSUE TITLE
roscore fails to start: Resource not found: roslaunch

### ISSUE THREAD

**Issue by soumith** [RoboStack/ros-noetic#171]
I did a fresh install of RoboStack with noetic.

I used a clean `mambaforge` install, and followed instructions here: https://robostack.github.io/GettingStarted.html

I ran the commands all the way uptill `mamba install ros-galactic-desktop`

After the install, I confirmed that `which roslaunch` and `which roscore` show valid binaries, and running `roslaunch` prints it's help.

Then, I run:

```
roscore
```

This fails with the following stack-trace:

```
roscore
WARNING: unable to configure logging. No log files will be generated
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: roslaunch
The traceback for the exception was written to the log file
Traceback (most recent call last):
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/config.py", line 451, in load_config_default
    load_roscore(loader, config, verbose=verbose)
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/config.py", line 92, in load_roscore
    f_roscore = get_roscore_filename()
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/roslaunch/config.py", line 84, in get_roscore_filename
    return os.path.join(r.get_path('roslaunch'), 'resources', 'roscore.xml')
  File "/home/soumith/mambaforge/envs/ros_env/lib/python3.8/site-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roslaunch
```

I checked that `self._location_cache` in line 207 of rospack.py is an empty dict `{}`.

Anyone see this issue before?

**Comment by soumith** [comment]
my bad, the fix was:

```
conda deactivate
conda activate ros_env
```

The env scripts never loaded without this.
