### ISSUE TITLE
Failed to import roslz4 package

### ISSUE THREAD

**Issue by nvander** [RoboStack/ros-noetic#391]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When attempting to import the `roslz4` module from `ros-noetic-roslz4`, it fails due to a missing `libpython2.7.so.1.0` library.

Here is the error I see:
```
(base) root@0441547fb234:~# python -c "import roslz4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/roslz4/__init__.py", line 33, in <module>
    from ._roslz4 import *
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

Here is the version of `ros-noetic-roslz4` I have installed:
```
(base) root@0441547fb234:~# micromamba list ros-noetic-roslz4
List of packages in environment: "/opt/conda"

  Name               Version  Build            Channel          
──────────────────────────────────────────────────────────────────
  ros-noetic-roslz4  1.15.15  py39hac30774_15  robostack-staging
```

Let me know if I can provide any additional detail that may be helpful. Thanks!

### Installed packages

```shell
List of packages in environment: "/opt/conda"

  Name                             Version       Build                Channel          
─────────────────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex                    0.1           conda_forge          conda-forge      
  _openmp_mutex                    4.5           2_gnu                conda-forge      
  apr                              1.7.0         h7f98852_5           conda-forge      
  binutils                         2.40          hdd6e379_0           conda-forge      
  binutils_impl_linux-64           2.40          hf600244_0           conda-forge      
  binutils_linux-64                2.40          hbdbef99_1           conda-forge      
  boost-cpp                        1.78.0        h2c5509c_4           conda-forge      
  bzip2                            1.0.8         h7f98852_4           conda-forge      
  c-ares                           1.19.1        hd590300_0           conda-forge      
  c-compiler                       1.6.0         hd590300_0           conda-forge      
  ca-certificates                  2023.7.22     hbcca054_0           conda-forge      
  catkin_pkg                       0.5.2         pyhd8ed1ab_0         conda-forge      
  cmake                            3.27.4        hcfe8598_4           conda-forge      
  console_bridge                   1.0.2         h924138e_1           conda-forge      
  cxx-compiler                     1.6.0         h00ab1b0_0           conda-forge      
  distro                           1.8.0         pyhd8ed1ab_0         conda-forge      
  docutils                         0.20.1        py39hf3d152e_0       conda-forge      
  empy                             3.3.4         pyh9f0ad1d_1         conda-forge      
  expat                            2.5.0         hcb278e6_1           conda-forge      
  gcc                              12.3.0        h8d2909c_1           conda-forge      
  gcc_impl_linux-64                12.3.0        he2b93b0_0           conda-forge      
  gcc_linux-64                     12.3.0        h76fc315_1           conda-forge      
  geos                             3.12.0        h59595ed_0           conda-forge      
  gettext                          0.21.1        h27087fc_0           conda-forge      
  gmock                            1.14.0        ha770c72_1           conda-forge      
  gmp                              6.2.1         h58526e2_0           conda-forge      
  gpgme                            1.18.0        h27087fc_0           conda-forge      
  gtest                            1.14.0        h00ab1b0_1           conda-forge      
  gxx                              12.3.0        h8d2909c_1           conda-forge      
  gxx_impl_linux-64                12.3.0        he2b93b0_0           conda-forge      
  gxx_linux-64                     12.3.0        h8a814eb_1           conda-forge      
  icu                              73.2          h59595ed_0           conda-forge      
  kernel-headers_linux-64          2.6.32        he073ed8_16          conda-forge      
  keyutils                         1.6.1         h166bdaf_0           conda-forge      
  krb5                             1.21.2        h659d440_0           conda-forge      
  ld_impl_linux-64                 2.40          h41732ed_0           conda-forge      
  libapr                           1.7.0         h7f98852_5           conda-forge      
  libapriconv                      1.2.2         h7f98852_5           conda-forge      
  libaprutil                       1.6.1         h975c496_5           conda-forge      
  libassuan                        2.5.6         h59595ed_0           conda-forge      
  libblas                          3.9.0         17_linux64_openblas  conda-forge      
  libcblas                         3.9.0         17_linux64_openblas  conda-forge      
  libcurl                          8.2.1         hca28451_0           conda-forge      
  libedit                          3.1.20191231  he28a2e2_2           conda-forge      
  libev                            4.33          h516909a_1           conda-forge      
  libexpat                         2.5.0         hcb278e6_1           conda-forge      
  libffi                           3.4.2         h7f98852_5           conda-forge      
  libgcc-devel_linux-64            12.3.0        h8bca6fd_0           conda-forge      
  libgcc-ng                        13.1.0        he5830b7_0           conda-forge      
  libgfortran-ng                   13.1.0        h69a702a_0           conda-forge      
  libgfortran5                     13.1.0        h15d22d2_0           conda-forge      
  libgomp                          13.1.0        he5830b7_0           conda-forge      
  libgpg-error                     1.47          h71f35ed_0           conda-forge      
  libiconv                         1.17          h166bdaf_0           conda-forge      
  liblapack                        3.9.0         17_linux64_openblas  conda-forge      
  libnghttp2                       1.52.0        h61bc06f_0           conda-forge      
  libnsl                           2.0.0         h7f98852_0           conda-forge      
  libopenblas                      0.3.23        pthreads_h80387f5_0  conda-forge      
  libsanitizer                     12.3.0        h0f45ef3_0           conda-forge      
  libsqlite                        3.43.0        h2797004_0           conda-forge      
  libssh2                          1.11.0        h0841786_0           conda-forge      
  libstdcxx-devel_linux-64         12.3.0        h8bca6fd_0           conda-forge      
  libstdcxx-ng                     13.1.0        hfd8a6a1_0           conda-forge      
  libuuid                          2.38.1        h0b41bf4_0           conda-forge      
  libuv                            1.46.0        hd590300_0           conda-forge      
  libzlib                          1.2.13        hd590300_5           conda-forge      
  log4cxx                          0.11.0        h291d653_3           conda-forge      
  lz4                              4.3.2         py39h724f13c_0       conda-forge      
  lz4-c                            1.9.4         hcb278e6_0           conda-forge      
  ncurses                          6.4           hcb278e6_0           conda-forge      
  netifaces                        0.11.0        py39hb9d737c_1       conda-forge      
  nose                             1.3.7         py_1006              conda-forge      
  numpy                            1.25.2        py39h6183b62_0       conda-forge      
  openssl                          3.1.2         hd590300_0           conda-forge      
  pip                              23.2.1        pyhd8ed1ab_0         conda-forge      
  pkg-config                       0.29.2        h36c2ea0_1008        conda-forge      
  poco                             1.12.4        h08a2579_0           conda-forge      
  pycryptodome                     3.18.0        py39h6f9bf71_0       conda-forge      
  pycryptodomex                    3.18.0        py39hd1e30aa_0       conda-forge      
  pyparsing                        3.1.1         pyhd8ed1ab_0         conda-forge      
  python                           3.9.13        h2660328_0_cpython   conda-forge      
  python-dateutil                  2.8.2         pyhd8ed1ab_0         conda-forge      
  python-gnupg                     0.5.0         pyhd8ed1ab_0         conda-forge      
  python_abi                       3.9           3_cp39               conda-forge      
  pyyaml                           6.0.1         py39hd1e30aa_0       conda-forge      
  readline                         8.2           h8228510_1           conda-forge      
  rhash                            1.4.4         hd590300_0           conda-forge      
  ros-distro-mutex                 0.4.0         noetic               robostack-staging
  ros-noetic-catkin                0.8.10        py39hac30774_15      robostack-staging
  ros-noetic-class-loader          0.5.0         py39hd72fd0a_15      robostack-staging
  ros-noetic-cpp-common            0.7.2         py39hc1d770b_15      robostack-staging
  ros-noetic-gencpp                0.7.0         py39hac30774_15      robostack-staging
  ros-noetic-geneus                3.0.0         py39hac30774_15      robostack-staging
  ros-noetic-genlisp               0.4.18        py39hac30774_15      robostack-staging
  ros-noetic-genmsg                0.6.0         py39hac30774_15      robostack-staging
  ros-noetic-gennodejs             2.0.2         py39hac30774_15      robostack-staging
  ros-noetic-genpy                 0.6.15        py39hac30774_15      robostack-staging
  ros-noetic-geometry-msgs         1.13.1        py39hac30774_15      robostack-staging
  ros-noetic-message-generation    0.4.1         py39hac30774_15      robostack-staging
  ros-noetic-message-runtime       0.4.13        py39hac30774_15      robostack-staging
  ros-noetic-pluginlib             1.13.0        py39h7534eef_15      robostack-staging
  ros-noetic-ros-environment       1.3.2         py39hac30774_15      robostack-staging
  ros-noetic-rosbag                1.15.15       py39h873cbd0_15      robostack-staging
  ros-noetic-rosbag-storage        1.16.0        py39hbd60425_15      robostack-staging
  ros-noetic-rosbuild              1.15.8        py39hac30774_15      robostack-staging
  ros-noetic-rosconsole            1.14.3        py39hc7694d4_15      robostack-staging
  ros-noetic-roscpp                1.15.15       py39h873cbd0_15      robostack-staging
  ros-noetic-roscpp-serialization  0.7.2         py39hac30774_15      robostack-staging
  ros-noetic-roscpp-traits         0.7.2         py39hac30774_15      robostack-staging
  ros-noetic-rosgraph              1.15.15       py39hac30774_15      robostack-staging
  ros-noetic-rosgraph-msgs         1.11.3        py39hac30774_15      robostack-staging
  ros-noetic-roslib                1.15.8        py39h873cbd0_15      robostack-staging
  ros-noetic-roslz4                1.15.15       py39hac30774_15      robostack-staging
  ros-noetic-rospack               2.6.2         py39h7534eef_15      robostack-staging
  ros-noetic-rospy                 1.15.15       py39hac30774_15      robostack-staging
  ros-noetic-rostime               0.7.2         py39h873cbd0_15      robostack-staging
  ros-noetic-std-msgs              0.5.13        py39hac30774_15      robostack-staging
  ros-noetic-std-srvs              1.11.3        py39hac30774_15      robostack-staging
  ros-noetic-topic-tools           1.15.15       py39hac30774_15      robostack-staging
  ros-noetic-xmlrpcpp              1.15.15       py39h873cbd0_15      robostack-staging
  rosdep                           0.22.2        pyhd8ed1ab_1         conda-forge      
  rosdistro                        0.9.0         py39hf3d152e_0       conda-forge      
  rospkg                           1.5.0         pyhd8ed1ab_0         conda-forge      
  setuptools                       68.1.2        pyhd8ed1ab_0         conda-forge      
  six                              1.16.0        pyh6c4a22f_0         conda-forge      
  sqlite                           3.43.0        h2c6b66d_0           conda-forge      
  sysroot_linux-64                 2.12          he073ed8_16          conda-forge      
  tinyxml2                         9.0.0         h9c3ff4c_2           conda-forge      
  tk                               8.6.12        h27826a3_0           conda-forge      
  tzdata                           2023c         h71feb2d_0           conda-forge      
  unixodbc                         2.3.12        h661eb56_0           conda-forge      
  wheel                            0.41.2        pyhd8ed1ab_0         conda-forge      
  xz                               5.2.6         h166bdaf_0           conda-forge      
  yaml                             0.2.5         h7f98852_2           conda-forge      
  zstd                             1.5.5         hfc55251_0           conda-forge
```

### Environment info

```shell
(base) root@0441547fb234:~# micromamba info

       libmamba version : 1.4.7
     micromamba version : 1.4.7
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /root/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=6.2.0=0
                          __glibc=2.31=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
```

**Comment by nvander** [comment]
OK, I may have been too quick to report this issue. It looks like the culprit may be a downstream pip install of the `bagpy` library may be clobbering some `roslz4` files. If I do an install of just `ros-noetic-roslz4` in a new environment, then the `roslz4` module imports just fine and I am able to work with lz4-compressed bag files.

Sorry for the trouble and thanks for being quick to respond!

**Comment by Tobias-Fischer** [comment]
Great to hear you managed to find the culprit! Baggy should be easy to move to conda forge via grayskull, give it a go if you like and let me know if you run into issues.
